[project]
name = "sdg-15"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Om Patil", email = "44ompatil@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
sdg-15 = "sdg_15:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
